kind: pipeline
type: docker
name: check-branch

platform:
  os: linux
  arch: arm

trigger:
  branch:
    - master

concurrency:
  limit: 1

clone:
  disable: true

steps:
  - name: clone
    image: 192.168.1.125:5000/cleep-git:latest
    network_mode: host
    privileged: true
    commands:
      - git clone $DRONE_REMOTE_URL cleep-cli
      - ls -la
      - cd cleep-cli
      - git checkout $DRONE_SOURCE_BRANCH

  - name: build
    image: 192.168.1.125:5000/cleep-twine/python3.7:20230116
    network_mode: host
    privileged: true
    commands:
      - python3 --version
      - cd cleep-cli
      - python3 setup.py clean
      - python3 setup.py sdist bdist_wheel --universal

  - name: publish
    image: 192.168.1.125:5000/cleep-twine/python3.7:20230116
    network_mode: host
    privileged: true
    environment:
      USERNAME:
        from_secret: PYPI_USERNAME
      PASSWORD:
        from_secret: PYPI_PASSWORD
    commands:
      - python3 -m twine --version
      - cd cleep-cli
      - ls -la
      - python3 -m twine upload -u $USERNAME -p $PASSWORD dist/*

